### ISSUE TITLE
Unit Testing broke with jackson-xml-databind on NinjaTest

### ISSUE THREAD

**Issue by cjmariano** [ninjaframework/ninja#528]
I am seeing the following on initialization when I run a junit test

`public class AuthenticationControllerTest extends NinjaTest {

```
@Test
public void testLogin() {
    UserCredentialBean payload = new UserCredentialBean();
    payload.setUsername("username");
    payload.setPassword("password");

    String result = ninjaTestBrowser.postJson(Routes.URL_LOGIN, payload);
}
```

}`

`14:41:14.730 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED o.e.j.s.ServletContextHandler@1199fe66{/,null,STARTING}: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withDefaultPrettyPrinter(Lcom/fasterxml/jackson/core/PrettyPrinter;)Lcom/fasterxml/jackson/databind/SerializationConfig;
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withDefaultPrettyPrinter(Lcom/fasterxml/jackson/core/PrettyPrinter;)Lcom/fasterxml/jackson/databind/SerializationConfig;
    at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:86)
    at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:71)`

jackson-xml-databind is not on active development right now. Maybe it broke when we upgraded `jackson from 2.5.1 to 2.8.1` . Also this happens as the unit test is bootstrapping.
